[TOR-2762] Added custom stylings for select with full border.
torchdental/torchbrand pull request #24
Opened 2021-03-01 20:43 UTC by ashraj98

[TOR-2762](https://torchdental.atlassian.net/browse/TOR-2762)

Separate stylings for select from standard input.
- Had to add a `select--wrapper` class so that `::after` could be used on the wrapper class to add in the chevron icon above the select.
- Added select sample to the component guide.

2021-03-04 19:44 UTC, pyen requested changes

2021-03-04 19:44 UTC, pyen commented on src/sass/_forms.scss
> +textarea {
Not sure removing default styles for the `select` tag is necessarily a good idea. Not all uses are classed with `select--wrapper`. A quick grep of `torchweb/static/app` shows some raw selects, including `BankAccountProfileForm.tsx`.


Can the wrapper styles be rewritten in a way that is compatible with (by overriding) the base `select` styles?

Alternately, ensure all downstream uses require `select--wrapper`, but considering those include `torchweb` as well as `torchdental` repositories, perhaps safer to have a base style for the `<select>` tag.

2021-03-04 19:44 UTC, pyen commented on src/sass/utility/mixins/_form-mixins.scss
> +}
This is effectively the same as:
```
  @include border-radius;
  border: $border--light;
```
This pair is in common enough usage that I'd suggest removing the mixin.

2021-03-05 20:45 UTC, ashraj98 commented on src/sass/_forms.scss
> +textarea {
I added it back. I was under the assumption we were updating the styles for all user-facing selects based on the ticket verbiage, so I removed it. I wrote the styles for `.select--wrapper select` before I took out `select` from where you noted, so all the new styles are overriding the old ones. I've added a screenshot as well for reference.

2021-03-05 20:45 UTC, ashraj98 commented on src/sass/utility/mixins/_form-mixins.scss
> +}
Gotcha, removed this.

2021-03-10 22:24 UTC, pyen approved these changes

2021-03-11 15:34 UTC, merged