[TOR-3208 supplement] Update font and container modifier options
torchdental/torchbrand pull request #52
Opened 2021-06-28 20:04 UTC by pazitschrecker

This PR adds new text modifiers (blue `h2` and `p`) with greater line height values. It also adds a container with extra padding. 

These additions are meant to support ticket [TOR-3208](https://torchdental.atlassian.net/browse/TOR-3208)

2021-06-30 19:22 UTC, pyen requested changes

2021-06-30 19:22 UTC, pyen commented on src/sass/components/_container.scss
> +    padding: $s64 $s80 !important ;
Where possible, it's preferred to avoid use of `!important` as it can unintentionally override other styles. It would be better to define this modifier without it, and consider its usage context carefully.

Generally speaking, we (Torch) control all of the HTML that goes into usage of any class here, so we should be able to changes classes to accomplish this. Feel free to ask for help on this one, as necessary.

2021-06-30 19:22 UTC, pyen commented on src/sass/_typography.scss
> +}
Ditto here on 1) global modifiers, 2) use of `!important`, and 3) line height.

Also, 4) this change does not appear in the `dist/css/torch-brand.css` diff above. Is one of these two files out of date?

2021-06-30 19:22 UTC, pyen commented on style_guide/js/app.js
> +            <div className={containerBlock('-extraPadding', 'buttonsLeft')}>
You may want to inspect the generated div in the browser's inspector. I suspect the `'-extraPadding'` class might not be rendered as `container--extraPadding`

2021-06-30 19:51 UTC, pazitschrecker commented on src/sass/components/_container.scss
> +    padding: $s64 $s80 !important ;
Good to know. 
Is there a reason used in this file for colors?

2021-06-30 20:26 UTC, pazitschrecker commented on style_guide/js/app.js
> +            <div className={containerBlock('-extraPadding', 'buttonsLeft')}>
It is rendering correctly.

2021-06-30 20:29 UTC, pazitschrecker commented on src/sass/_typography.scss
> +}
Replaced with a test-- class and removed !important

2021-06-30 23:00 UTC, pyen commented on src/sass/components/_container.scss
> +    padding: $s64 $s80 !important ;
That's a good question. I suppose it's because colors may desire high specificity instead of rewriting the DOM structure to get a more favorable style.

The structure of CSS sort of conspires towards the use of `!important`: if you have color applied by CSS  that depends on structure, it may be more specific than the text you are trying to color. Here's a totally contrived but illustrative example:
``` css
.gray .price {
  /* we default all prices to be gray */
  color: gray;
}
.green {
  /* we may want to make it green if it's in stock */
  color: green;
}
```
``` html
<div class="gray">
  <span class="green">$4.00</span>
</div>
```
https://codesandbox.io/s/sharp-newton-owimz?file=/index.html

Even in this example, it's worth noting we could rewrite the structure, but it's often easier to apply the utility class.

2021-07-01 16:37 UTC, pyen approved these changes
Just one removal and we're good to go.

2021-07-01 16:37 UTC, pyen commented on src/sass/_typography.scss
> +}
Let's also remove this one.

2021-07-01 16:42 UTC, merged